### ISSUE TITLE
如何使用啊（手动狗头）

### ISSUE THREAD

**Issue by VNRKDOEA** [ja-netfilter/plugin-power#1]

**Comment by pengzhile** [comment]
写写配置文件么

**Comment by VNRKDOEA** [comment]
> 写写配置文件么

大佬是lice 、grac、paid这三个吗，写了没生效啊，写在arg还是result里

**Comment by pengzhile** [comment]
你这是mymap的配置，不是power的。它们俩是共存分别实现各自功能的关系，不是替代。

**Comment by VNRKDOEA** [comment]
> 你这是mymap的配置，不是power的。它们俩是共存分别实现各自功能的关系，不是替代。

power的是什么
