### ISSUE TITLE
【windows】cann't generate xx.jvmoptions

### ISSUE THREAD

**Issue by zsr228** [ja-netfilter/plugin-power#4]
cmd run:
`goland.bat configure -J"javaagent:D:\ja-netfilter\ja-netfilter.jar"`
error is:
![image](https://user-images.githubusercontent.com/22949549/150943210-5fa767e5-e379-4982-96fc-66c29388b121.png)
![image](https://user-images.githubusercontent.com/22949549/150943502-500ce5df-74f9-4835-b41b-68239a1054ed.png)

then run 
`goland.bat configure -J"javaagent=/ja-netfilter/ja-netfilter.jar"`
![image](https://user-images.githubusercontent.com/22949549/150943857-c128d9f5-3846-4ae4-a85b-b42a9ebff606.png)

nothing generate

**Comment by pengzhile** [comment]
Where did you learn all these puzzling operations?

**Comment by zsr228** [comment]
read error
